spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jesusyapiko/microservices-course-config-repo
          default-label: master
server:
  port: '8888'
